### PR TITLE
Converted the code snippet to be in swift 3

### PR DESCRIPTION
**Pull request by shubh10**
The code snippet in _readme_ file was not entirely in swift, for e.g the method declaration was missing `func` keyword and method parenthesis _**()**_.
Also at `NSURL` initialization the code was following Objective syntax, converted it to swift3 now.

### CODE REVIEW

**Comment by insanelydeepak** [comment]
Thanks

**Comment by insanelydeepak** [comment]
Hi 
this is not Swift Project

**Comment by shubh10** [comment]
Well then why does the code snippet example have swift syntax. Either completely change the syntax to swift or objective-c, you're killing me with mixed syntax her :p

**Comment by insanelydeepak** [comment]
ok check now

**Comment by insanelydeepak** [comment]
BTW good catch

**Comment by shubh10** [comment]
Thanks.

**Pull request merged**
